# Site
repository: cyberscribbleorg/cyberscribbleorg.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pragash Jeyaratnam
title: Engineer ( B.Sc | CEH | CSM )
email: pragash.jeyaratnam@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  cyberscribbleorg
stackoverflow_username: "choppe"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: pragashj
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pragash and I'm an Engineering Practitioner. On top of wiring things, I am passionate about building interesting tools out of curiosity. 
  I am most skilled in: <mark>Embedded Systems</mark>,  <mark>Security</mark> and <mark>Cooking</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Cyber Scribble Blog
        link: https://www.cyberscribble.org
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          CyberScribble is an innovative blog dedicated to exploring and educating on the latest in cybersecurity and tech trends.
      - layout: top-middle
        title: GED
        link: https://git-event-dash.onrender.com/
        description: | # this will include new lines to allow paragraphs
          This gitHub events dashboard provides a comprehensiveview of opensource github events.        
      - layout: top-middle
        title: Top N GED
        link: https://top-proj-dash.onrender.com/
        description: | # this will include new lines to allow paragraphs
          This GitHub events dashboard provides a comprehensiveview activities for Top N project open source projects.              
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Security Compass
        link: https://wwww.securitycompass.com
        # link_text: boringcompany.com
        sub_title: Lead, Software Development
        caption: Jan 2023 - Mar 2024
        

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University Of Moratuwa
        caption: 2001 - 2005
        sub_title: BSc Engineering in Electronics & Telecommunications 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
